# diff-risk.skill.yaml
# Claude Code Skill: Risk-focused diff analysis using branch-narrator
#
# Usage: /diff-risk [--threshold <score>] [--categories <list>]
#
# This skill provides AI agents with risk assessment of code changes,
# including evidence-backed flags, score breakdown, and recommendations.

apiVersion: claude.ai/v1
kind: Skill
metadata:
  name: diff-risk
  displayName: Diff Risk
  description: Get risk assessment of current changes with evidence-backed flags and score breakdown
  category: development
  tags:
    - git
    - risk
    - security
    - code-review
    - ci-cd
  version: "1.0.0"
  author: "@better-vibe/branch-narrator"

spec:
  trigger: /diff-risk

  help: |
    Assess risk of current changes with evidence and recommendations.

    Usage:
      /diff-risk                    # Full risk assessment
      /diff-risk --threshold 50     # Highlight if score >= 50
      /diff-risk --only security,db # Focus on specific categories

    Risk levels:
      - 0-20: Low
      - 21-40: Moderate
      - 41-60: Elevated
      - 61-80: High
      - 81-100: Critical

    Categories: security, deps, db, infra, config, api, tests

  arguments:
    - name: mode
      type: string
      short: m
      default: unstaged
      enum: [unstaged, staged, all, branch]
      description: Which changes to analyze

    - name: threshold
      type: number
      short: t
      default: 50
      description: Risk score threshold to highlight concerns

    - name: only
      type: string
      short: o
      required: false
      description: Comma-separated categories to include (e.g., security,db)

    - name: exclude
      type: string
      short: x
      required: false
      description: Comma-separated categories to exclude

    - name: redact
      type: boolean
      short: r
      default: false
      description: Redact secret values in evidence

  execution:
    tool: bash
    workdir: "{{ cwd }}"

    command: |
      branch-narrator risk-report \
        --mode {{ args.mode }} \
        {{ if args.only }}--only {{ args.only }}{{ end }} \
        {{ if args.exclude }}--exclude {{ args.exclude }}{{ end }} \
        {{ if args.redact }}--redact{{ end }} \
        --explain-score \
        --format json \
        --pretty \
        --no-timestamp

    timeout: 30000

  output:
    format: json
    injection: context

    summary_template: |
      **Risk Assessment: {{ .score }}/100 ({{ .level }})**
      {{ if ge .score args.threshold }}⚠️ Exceeds threshold of {{ args.threshold }}{{ end }}

      **Top Flags:**
      {{ range (slice .flags 0 5) }}- [{{ .severity }}] {{ .message }}
      {{ end }}

    # Highlight in UI if risk exceeds threshold
    highlight_condition: "{{ .score }} >= {{ args.threshold }}"

  cache:
    key_strategy: git-status-hash
    ttl: 300

  requires:
    command:
      name: branch-narrator
      version: ">=1.5.0"
