# diff-raw.skill.yaml
# Claude Code Skill: AI-optimized raw diff using branch-narrator
#
# Usage: /diff-raw [--mode <mode>] [--unified <n>]
#
# This skill provides filtered, AI-optimized diff output
# with smart exclusions and optional chunking.

apiVersion: claude.ai/v1
kind: Skill
metadata:
  name: diff-raw
  displayName: Diff Raw
  description: Get AI-optimized raw diff with smart filtering
  category: development
  tags:
    - git
    - diff
    - raw
    - code
  version: "1.0.0"
  author: "@better-vibe/branch-narrator"

spec:
  trigger: /diff-raw

  help: |
    Get filtered raw diff optimized for AI analysis.

    Usage:
      /diff-raw                    # All unstaged changes
      /diff-raw --unified 5        # More context lines
      /diff-raw --include "src/**" # Only src files

    Automatically excludes:
      - Lock files (package-lock.json, etc.)
      - Build artifacts (dist/, .next/, etc.)
      - Minified files (*.min.js)
      - Binary files

  arguments:
    - name: mode
      type: string
      short: m
      default: unstaged
      enum: [unstaged, staged, all, branch]
      description: Which changes to show

    - name: unified
      type: number
      short: u
      default: 3
      description: Lines of unified context

    - name: include
      type: string
      short: i
      required: false
      description: Glob pattern to include (can be repeated)

    - name: exclude
      type: string
      short: x
      required: false
      description: Additional glob pattern to exclude

    - name: max_chars
      type: number
      default: 100000
      description: Maximum output characters (truncate if exceeded)

    - name: stat
      type: boolean
      short: s
      default: false
      description: Show file statistics instead of diff

    - name: name_only
      type: boolean
      short: n
      default: false
      description: Show file names only

  execution:
    tool: bash
    workdir: "{{ cwd }}"

    command: |
      branch-narrator dump-diff \
        --mode {{ args.mode }} \
        --unified {{ args.unified }} \
        {{ if args.include }}--include "{{ args.include }}"{{ end }} \
        {{ if args.exclude }}--exclude "{{ args.exclude }}"{{ end }} \
        {{ if args.stat }}--stat{{ end }} \
        {{ if args.name_only }}--name-only{{ end }} \
        --format text

    timeout: 30000

  output:
    format: text
    injection: context

    # Truncate if too large
    max_length: "{{ args.max_chars }}"
    truncation_message: "[Diff truncated at {{ args.max_chars }} chars. Use --include to filter.]"

  cache:
    key_strategy: git-status-hash
    ttl: 300

  requires:
    command:
      name: branch-narrator
      version: ">=1.5.0"
